###############
steps:
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:slim'
    entrypoint: 'gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'astro-app' #Service name
      - '--image'
      - 'gcr.io/$PROJECT_ID/astro-app' #project: genai-proj-1, image: astro-app
      - '--region'
      - 'asia-south1'
      - '--set-secrets'
      - 'PINECONE_API_KEY=PINECONE_API_KEY'
      - 'GOOGLE_API_KEY=GOOGLE_API_KEY'
      - 'OPENCAGE_API_KEY=OPENCAGE_API_KEY'